name: Judy testing the grid
favicon: null
layout_spectrum: 0.03648847225122154
typography_spectrum: 0.8372199423611164
title: 'Tower Bridge '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050308'
    - '#a1b3cb'
    - '#feffff'
    - '#2f4666'
    - '#80783a'
  brandStrength: 0.5
  lightness: 0.919691426679492
  saturation: 0.41547746723517776
  rhythmicContrast: 0.07229106011800468
purpose: []
